# Generated by Django 3.2.9 on 2022-03-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('re_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('robot', models.CharField(max_length=100)),
                ('QQ', models.IntegerField(max_length=64)),
                ('re_QQ', models.IntegerField(max_length=64)),
                ('send_time', models.IntegerField(max_length=64)),
            ],
        ),
    ]
